### ISSUE TITLE
Getting error "TypeError: Cannot read property 'exact' of null" when calling "getByTestId" in react testing library.

### ISSUE THREAD

**Issue by pj** [Shmew/Fable.Jester#5]
## Description
Hi there, I'm getting an error "TypeError: Cannot read property 'exact' of null" when calling "getByTestId" in react test library. From the javascript code it looks like it's passing null as the option to the underlying queryAllByAttribute function, though it looks like it should work? Maybe it needs to be undefined?

I'm running this on Mac and it's failing with node 12 and 14.

## Steps to reproduce

Example broken test code:

```fsharp
module Test
open Fable.React.Standard
open Fable.React.Helpers
open Fable.Jester
open Fable.ReactTestingLibrary
open Fable.React.Props
open Feliz

let testElement = React.functionComponent(fun () ->
    Html.h1 [
        prop.testId "test"
        prop.text "Hello World"
    ]
  )

Jest.describe("blah", fun () ->
  Jest.test("props", fun () ->
    let result = RTL.render(testElement())
    result.debug ()
    let testElement = result.getByTestId "test"
    Jest.expect(testElement).toHaveTextContent("Hello World")
  )
)
```

If I change the line: 
`    let testElement = result.getByTestId "test"`

It works when I add an explicit empty array argument
`    let testElement = result.getByTestId("test", [])`

## Expected behavior
Just passing string should work as expected, or behavior should be documented.

**Comment by Shmew** [comment]
Hi @pj, 

Can you confirm what version of `fable-compiler` you're on? I suspect you're using an old version as I can't reproduce. Running `npm update`/`yarn upgrade` should resolve this.

You can see the query tests for testId which I updated to be more explicit and cover your cases [here](https://github.com/Shmew/Fable.Jester/blob/master/tests/Fable.ReactTestingLibrary.Tests/Queries/TestId.test.fs).

You can see all the tests pass via CI [here](https://ci.appveyor.com/project/Shmew/fable-jester/builds/35022547#L888).

**Comment by pj** [comment]
Thanks, that did it!
